// <auto-generated />
using System;
using ClientWOE.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClientWOE.API.Migrations
{
    [DbContext(typeof(WoeDbContext))]
    partial class WoeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClientWOE.API.Models.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientId"));

                    b.Property<string>("ClientCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("ClientId");

                    b.HasIndex("ClientCode")
                        .IsUnique();

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            ClientId = 1,
                            ClientCode = "CLI001",
                            ClientName = "Apollo Diagnostics",
                            IsActive = true
                        },
                        new
                        {
                            ClientId = 2,
                            ClientCode = "CLI002",
                            ClientName = "City Care Hospital",
                            IsActive = true
                        },
                        new
                        {
                            ClientId = 3,
                            ClientCode = "CLI003",
                            ClientName = "Walk-In Client",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("ClientWOE.API.Models.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientId"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("PatientCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PatientId");

                    b.HasIndex("ClientId");

                    b.HasIndex("PatientCode")
                        .IsUnique();

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("ClientWOE.API.Models.TestMaster", b =>
                {
                    b.Property<int>("TestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TestId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TestCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TestName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("TestId");

                    b.HasIndex("TestCode")
                        .IsUnique();

                    b.ToTable("TestMasters");

                    b.HasData(
                        new
                        {
                            TestId = 1,
                            IsActive = true,
                            Rate = 350m,
                            TestCode = "CBC",
                            TestName = "Complete Blood Count"
                        },
                        new
                        {
                            TestId = 2,
                            IsActive = true,
                            Rate = 150m,
                            TestCode = "FBS",
                            TestName = "Fasting Blood Sugar"
                        },
                        new
                        {
                            TestId = 3,
                            IsActive = true,
                            Rate = 700m,
                            TestCode = "LFT",
                            TestName = "Liver Function Test"
                        },
                        new
                        {
                            TestId = 4,
                            IsActive = true,
                            Rate = 650m,
                            TestCode = "KFT",
                            TestName = "Kidney Function Test"
                        },
                        new
                        {
                            TestId = 5,
                            IsActive = true,
                            Rate = 550m,
                            TestCode = "LIPID",
                            TestName = "Lipid Profile"
                        },
                        new
                        {
                            TestId = 6,
                            IsActive = true,
                            Rate = 300m,
                            TestCode = "TSH",
                            TestName = "TSH"
                        });
                });

            modelBuilder.Entity("ClientWOE.API.Models.WorkOrder", b =>
                {
                    b.Property<int>("WorkOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkOrderId"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("WoeNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("WorkOrderId");

                    b.HasIndex("ClientId");

                    b.HasIndex("PatientId");

                    b.HasIndex("WoeNumber")
                        .IsUnique();

                    b.ToTable("WorkOrders");
                });

            modelBuilder.Entity("ClientWOE.API.Models.WorkOrderTestDetail", b =>
                {
                    b.Property<int>("WorkOrderTestDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkOrderTestDetailId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TestId")
                        .HasColumnType("int");

                    b.Property<int>("WorkOrderId")
                        .HasColumnType("int");

                    b.HasKey("WorkOrderTestDetailId");

                    b.HasIndex("TestId");

                    b.HasIndex("WorkOrderId");

                    b.ToTable("WorkOrderTestDetails");
                });

            modelBuilder.Entity("ClientWOE.API.Models.Patient", b =>
                {
                    b.HasOne("ClientWOE.API.Models.Client", "Client")
                        .WithMany("Patients")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("ClientWOE.API.Models.WorkOrder", b =>
                {
                    b.HasOne("ClientWOE.API.Models.Client", "Client")
                        .WithMany("WorkOrders")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClientWOE.API.Models.Patient", "Patient")
                        .WithMany("WorkOrders")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("ClientWOE.API.Models.WorkOrderTestDetail", b =>
                {
                    b.HasOne("ClientWOE.API.Models.TestMaster", "TestMaster")
                        .WithMany("WorkOrderTestDetails")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClientWOE.API.Models.WorkOrder", "WorkOrder")
                        .WithMany("TestDetails")
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestMaster");

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("ClientWOE.API.Models.Client", b =>
                {
                    b.Navigation("Patients");

                    b.Navigation("WorkOrders");
                });

            modelBuilder.Entity("ClientWOE.API.Models.Patient", b =>
                {
                    b.Navigation("WorkOrders");
                });

            modelBuilder.Entity("ClientWOE.API.Models.TestMaster", b =>
                {
                    b.Navigation("WorkOrderTestDetails");
                });

            modelBuilder.Entity("ClientWOE.API.Models.WorkOrder", b =>
                {
                    b.Navigation("TestDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
